#!/usr/bin/env bash
# macOS only: installs the Blenny GUI onto the Desktop so you get a proper
# double-clickable icon (with the blenny artwork) that launches the GUI in a
# Terminal window. Double-click this file in Finder to run it.
#
# Unlike the repo-root "Blenny GUI.app" bundle (which resolves the launcher
# relative to itself and therefore works wherever the repo lives), a copy on
# the Desktop sits *outside* the repo and cannot locate scripts/launch_gui.sh
# on its own. So this script bakes the repo's absolute path into the Desktop
# copy's launcher. Re-run the script if you move the repo.
set -e

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$HOME/Desktop/Blenny GUI.app"

if [ ! -d "$REPO/Blenny GUI.app" ]; then
    echo "Could not find 'Blenny GUI.app' in the repository root: $REPO"
    exit 1
fi

rm -rf "$DEST"
cp -R "$REPO/Blenny GUI.app" "$DEST"

# Bake the repo path into the Desktop copy's launcher.
cat > "$DEST/Contents/MacOS/launcher" <<EOF
#!/usr/bin/env bash
# Generated by scripts/create_macos_shortcut.command — points at the repo at
# $REPO. Re-run the script if you move the repo.
set -u
LAUNCHER="$REPO/scripts/launch_gui.sh"
if [ ! -f "\$LAUNCHER" ]; then
    osascript -e "display alert \"Blenny GUI\" message \"Could not find scripts/launch_gui.sh at \$LAUNCHER.\"" 2>/dev/null || true
    exit 1
fi
osascript -e "tell application \\\"Terminal\\\" to do script \\\"cd '$REPO' && exec bash '\$LAUNCHER'\\\"" || exec "\$LAUNCHER"
EOF
chmod +x "$DEST/Contents/MacOS/launcher"

# If the repo came from a download/zip, drop the quarantine flag that macOS
# uses to block first launch of unsigned apps.
xattr -dr com.apple.quarantine "$DEST" 2>/dev/null || true

echo "Installed 'Blenny GUI' on the Desktop."
echo "Double-click it to launch the plate reader GUI (close the window to stop)."
